In [1]:

name = "Dr. Heinz Doofenshmirtz"
city = "Tri-State-Area"
SSN = 18245

print ("Name = ", name)
print("City = ", city)
print("SSN = ", SSN)

print("I'm {}, from {} and my SSN is {}".format(name,city,SSN))

Name =  Dr. Heinz Doofenshmirtz
City =  Tri-State-Area
SSN =  18245
I'm Dr. Heinz Doofenshmirtz, from Tri-State-Area and my SSN is 18245


In [ ]:
info = [name,city,SSN]

for element in info:
    if(type(element) == str):
        print(element)
    else:
        print("ha you thought")


In [30]:
import numpy as np #type:ignore
x=np.linspace(0,5,6)
print(x)
y = np.zeros(11)
#print(y)
z = np.arange(0,5+0.5,0.5)
#print(z)

print(x[0:2]) #prints the first two entries in list
print(x[:-2]) #prints all but the last two entries
print(x[1:]) #prints all but the first entry

[0. 1. 2. 3. 4. 5.]
[0. 1.]
[0. 1. 2. 3.]
[1. 2. 3. 4. 5.]


In [31]:
#2D Arrays
X = np.meshgrid(x,x)
X=X[0]
print(X)
print('\n')

from tabulate import tabulate #type:ignore

column = [(X[0])[0],(X[1])[0], (X[2])[0], (X[3])[0], (X[4])[0], (X[5])[0]]

def getColumn(two_array, column_num):
    amount_col = len(two_array)
    temp_column = np.zeros(amount_col)
    for i in range(0,6):
        temp_column[i] = two_array[i][column_num]
    return(temp_column)


showCol = [
    ['Column 1', getColumn(X,0)]
]

print(tabulate(showCol))

[[0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]]




ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
import pandas as pd #type:ignore

pd.read_csv(filename, delim_whitespace=True,skiprows=1,names=['x','z'])